name: Package Release Workflow

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "idk"
		
      - name: step2
        run: echo "there will be cool commands here"